[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
blur = true
dynamic_padding = true
opacity = 0.9
padding = { x = 5, y = 5 }
resize_increments = true
title = "Alacritty"

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Regular" }
size = 12

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Underline" }

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", action = "PasteSelection" }]

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "W", mods = "Control|Shift", action = "Quit" },
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]
