#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
disable_notice = true
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[var]
  sepl = '<p:separator>❬</>'
  sepld = '<p:separator>-❬</>'
  sepr = '<p:separator>❭</>'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = 'p:root'
    template = ' '

  [[blocks.segments]]
    type='os'
    style='plain'
    foreground = 'p:os'
    template='{{ .Var.sepl }}{{ .UserName }}{{ .Icon }} {{ if .WSL }}WSL @{{ end }} {{ .HostName }}{{ .Var.sepr }}'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:text'
    template = '{{ .Var.sepld }}{{ path .Path .Location }}{{ .Var.sepr }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:py'
    template = '{{ .Var.sepld }} {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ end }}{{ .Var.sepr }}'

    [blocks.segments.properties]
      display_mode = 'context'

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = 'p:node'
    template = '{{ .Var.sepld }}󰎙 {{if .Error}}{{ .Error }} {{ else }}{{ .Major }}{{ end }}{{ .Var.sepr }}'

    [blocks.segments.properties]
      display_mode = 'context'


  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:git'
    template = '{{ .Var.sepld }}{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ .Var.sepr }}'

    [blocks.segments.properties]
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:text'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 500

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{ if gt .Code 0 }}p:error{{ end }}',
      'p:text',
    ]
    template = '❱'

[transient_prompt]
  foreground_templates = [
    '{{ if gt .Code 0 }}p:error{{ end }}',
    'p:text',
  ]
  template = '{{ .PWD }} ❱ '

[secondary_prompt]
  foreground = 'p:text'
  template = '❱❱ '

[palette]
  text      = 'lightBlue'
  error     = 'lightRed'
  root      = 'red'
  separator = 'green'
  py        = 'lightYellow'
  node      = 'lightGreen'
  git       = 'lightWhite'
  os       = 'lightMagenta'
